[
  {
    prev_league_id: null,
    image_list: [],
    banner_list: null,
    is_talk_online: false,
    award_list: null,
    push_send_status: {},
    performer_name: "",
    follower_num: 121622,
    live_continuous_days: 0,
    next_league_id: null,
    live_id: 0,
    league_id: 0,
    is_official: true,
    is_follow: false,
    voice_list: [],
    show_rank_subdivided: "Excluded",
    event: null,
    is_birthday: false,
    description:
      "Name: Amanda Puspita Sukma Mulyadewi\r\nBirthday: 17 December 2004\r\nBirthplace: Malang\r\nBlood type: O\r\nZodiac signs:  Sagitarius\r\nHobby: Dance, Automotive\r\n\r\nTwitter: PS_AmandaJKT48\r\nInstagram:jkt48.amanda.s",
    live_tags: [],
    genre_id: 102,
    displayed_medals: [],
    prev_score: 0,
    youtube_id: "eq0s1atl_K0",
    visit_count: 0,
    recommend_comment_list: [
      {
        created_at: 1688458828,
        comment: "lagi ngapain ",
        user: {
          name: "Yosi",
          image:
            "https://static.showroom-live.com/image/avatar/1062555.png?v=95",
        },
      },
      {
        created_at: 1688458803,
        comment: "lah",
        user: {
          name: "Fynnxz ohayoouu",
          image:
            "https://static.showroom-live.com/image/avatar/1063445.png?v=95",
        },
      },
      {
        created_at: 1688460092,
        comment: "Salam Kenal ya manda",
        user: {
          name: "Adhywira_13",
          image:
            "https://static.showroom-live.com/image/avatar/1033835.png?v=95",
        },
      },
    ],
    current_live_started_at: 0,
    next_show_rank_subdivided: "",
    share_text_live:
      "Amanda/アマンダ（JKT48） Broadcasting!\nhttps://www.showroom-live.com/r/JKT48_Amanda?t=1689385362",
    sns_list: [
      {
        icon: "https://static.showroom-live.com/assets/img/icon/sns/youtube.png",
        url: "https://www.youtube.com/watch?v=eq0s1atl_K0",
        name: "Youtube",
      },
    ],
    recommend_comments_url:
      "https://www.showroom-live.com/room/recommend_comments?room_id=400710",
    share_url: "https://www.showroom-live.com/room/profile?room_id=400710",
    room_url_key: "JKT48_Amanda",
    league_label: "",
    is_live_tag_campaign_opened: false,
    avatar: null,
    share_url_live: "https://www.showroom-live.com/r/JKT48_Amanda?t=1689385362",
    prev_show_rank_subdivided: "",
    is_talk_opened: false,
    image_square:
      "https://static.showroom-live.com/image/room/cover/2f2a93fe26c52af0bb33db6044b796b9590efd9ed198b852184820bd9845fef6_square_m.jpeg?v=1685542722",
    recommend_comment_post_url:
      "https://www.showroom-live.com/room/recommend_comments?room_id=400710#post",
    genre_name: "Idol",
    room_name: "Amanda/アマンダ（JKT48）",
    birthday: 93366000,
    room_level: 80,
    party_live_status: 0,
    party: {},
    ec_config: { sales_available: 0, is_external_ec: 0, links: [] },
    image:
      "https://static.showroom-live.com/image/room/cover/2f2a93fe26c52af0bb33db6044b796b9590efd9ed198b852184820bd9845fef6_m.jpeg?v=1685542722",
    recommend_comment_open_status: 1,
    main_name: "Amanda/アマンダ（JKT48）",
    view_num: 0,
    has_more_recommend_comment: true,
    is_party_enabled: false,
    premium_room_type: 0,
    next_score: 0,
    is_onlive: false,
    room_id: 400710,
  },
  {
    prev_league_id: null,
    image_list: [],
    banner_list: null,
    is_talk_online: false,
    award_list: null,
    push_send_status: {},
    performer_name: "",
    follower_num: 124787,
    live_continuous_days: 1,
    next_league_id: null,
    live_id: 0,
    league_id: 0,
    is_official: true,
    is_follow: false,
    voice_list: [],
    show_rank_subdivided: "Excluded",
    event: null,
    is_birthday: false,
    description:
      "Name: Aurellia\r\nBirthday: 29 Oktober 2002\r\nBirthplace: Jakarta\r\nBlood type: O\r\nZodiac signs:  Scorpio\r\nHobby: Dance, Listening to Music\r\n\r\nTwitter: AU_LiaJKT48\r\nInstagram: jkt48.aurellia_",
    live_tags: [],
    genre_id: 102,
    displayed_medals: [],
    prev_score: 0,
    youtube_id: "eq0s1atl_K0",
    visit_count: 0,
    recommend_comment_list: [
      {
        created_at: 1689352872,
        comment: "sapa aku boleh ga",
        user: {
          name: "Abenx",
          image: "https://static.showroom-live.com/image/avatar/24.png?v=95",
        },
      },
      {
        created_at: 1689352333,
        comment: "aurell",
        user: {
          name: "coklatMuu",
          image: "https://static.showroom-live.com/image/avatar/5.png?v=95",
        },
      },
      {
        created_at: 1689352412,
        comment: "Cici 🤍",
        user: {
          name: "EL Fathan",
          image:
            "https://static.showroom-live.com/image/avatar/1041035.png?v=95",
        },
      },
    ],
    current_live_started_at: 0,
    next_show_rank_subdivided: "",
    share_text_live:
      "Lia /リア（JKT48） Broadcasting!\nhttps://www.showroom-live.com/r/JKT48_Lia?t=1689385362",
    sns_list: [
      {
        icon: "https://static.showroom-live.com/assets/img/icon/sns/youtube.png",
        url: "https://www.youtube.com/watch?v=eq0s1atl_K0",
        name: "Youtube",
      },
    ],
    recommend_comments_url:
      "https://www.showroom-live.com/room/recommend_comments?room_id=400713",
    share_url: "https://www.showroom-live.com/room/profile?room_id=400713",
    room_url_key: "JKT48_Lia",
    league_label: "",
    is_live_tag_campaign_opened: false,
    avatar: null,
    share_url_live: "https://www.showroom-live.com/r/JKT48_Lia?t=1689385362",
    prev_show_rank_subdivided: "",
    is_talk_opened: false,
    image_square:
      "https://static.showroom-live.com/image/room/cover/104f71ef35980e70baeb6a7ed59f18c7374f9a33bf7d1720a0581b8a0b2edb1e_square_m.jpeg?v=1685542598",
    recommend_comment_post_url:
      "https://www.showroom-live.com/room/recommend_comments?room_id=400713#post",
    genre_name: "Idol",
    room_name: "Lia /リア（JKT48）",
    birthday: 89132400,
    room_level: 115,
    party_live_status: 0,
    party: {},
    ec_config: { sales_available: 0, is_external_ec: 0, links: [] },
    image:
      "https://static.showroom-live.com/image/room/cover/104f71ef35980e70baeb6a7ed59f18c7374f9a33bf7d1720a0581b8a0b2edb1e_m.jpeg?v=1685542598",
    recommend_comment_open_status: 1,
    main_name: "Lia /リア（JKT48）",
    view_num: 0,
    has_more_recommend_comment: true,
    is_party_enabled: false,
    premium_room_type: 0,
    next_score: 0,
    is_onlive: false,
    room_id: 400713,
  },
  {
    prev_league_id: null,
    image_list: [],
    banner_list: null,
    is_talk_online: false,
    award_list: null,
    push_send_status: {},
    performer_name: "",
    follower_num: 127181,
    live_continuous_days: 0,
    next_league_id: null,
    live_id: 0,
    league_id: 0,
    is_official: true,
    is_follow: false,
    voice_list: [],
    show_rank_subdivided: "Excluded",
    event: null,
    is_birthday: false,
    description:
      "Name: Callista Alifia Wardhana\r\nBirthday: 8 August 2005\r\nBirthplace: Jakarta\r\nBlood type: O\r\nZodiac signs:  Leo\r\nHobby: Dance, Listening to Music\r\n\r\nTwitter: AW_CallieJKT48",
    live_tags: [],
    genre_id: 102,
    displayed_medals: [],
    prev_score: 0,
    youtube_id: "eq0s1atl_K0",
    visit_count: 0,
    recommend_comment_list: [
      {
        created_at: 1689342442,
        comment: "Hello Callie-san! How ya goin'?",
        user: {
          name: "Timothy Natanael Sebastian",
          image: "https://static.showroom-live.com/image/avatar/6.png?v=95",
        },
      },
      {
        created_at: 1688823017,
        comment: "kak callie sr dong\n",
        user: {
          name: "AbulCallie7",
          image: "https://static.showroom-live.com/image/avatar/6.png?v=95",
        },
      },
      {
        created_at: 1686954711,
        comment: "kell..kpn kmu sr lgi ???\nkmi kangen lho liat kmu sr.",
        user: {
          name: "Syana_LvJg",
          image: "https://static.showroom-live.com/image/avatar/1.png?v=95",
        },
      },
    ],
    current_live_started_at: 0,
    next_show_rank_subdivided: "",
    share_text_live:
      "Callie /カリー（JKT48） Broadcasting!\nhttps://www.showroom-live.com/r/JKT48_Callie?t=1689385362",
    sns_list: [
      {
        icon: "https://static.showroom-live.com/assets/img/icon/sns/youtube.png",
        url: "https://www.youtube.com/watch?v=eq0s1atl_K0",
        name: "Youtube",
      },
    ],
    recommend_comments_url:
      "https://www.showroom-live.com/room/recommend_comments?room_id=400714",
    share_url: "https://www.showroom-live.com/room/profile?room_id=400714",
    room_url_key: "JKT48_Callie",
    league_label: "",
    is_live_tag_campaign_opened: false,
    avatar: null,
    share_url_live: "https://www.showroom-live.com/r/JKT48_Callie?t=1689385362",
    prev_show_rank_subdivided: "",
    is_talk_opened: false,
    image_square:
      "https://static.showroom-live.com/image/room/cover/8b558b8317e4ec4aa4d6afdb9c7c62675cdd352a49bf2a42d2900ec35aa32a67_square_m.jpeg?v=1685542636",
    recommend_comment_post_url:
      "https://www.showroom-live.com/room/recommend_comments?room_id=400714#post",
    genre_name: "Idol",
    room_name: "Callie /カリー（JKT48）",
    birthday: 82047600,
    room_level: 53,
    party_live_status: 0,
    party: {},
    ec_config: { sales_available: 0, is_external_ec: 0, links: [] },
    image:
      "https://static.showroom-live.com/image/room/cover/8b558b8317e4ec4aa4d6afdb9c7c62675cdd352a49bf2a42d2900ec35aa32a67_m.jpeg?v=1685542636",
    recommend_comment_open_status: 1,
    main_name: "Callie /カリー（JKT48）",
    view_num: 0,
    has_more_recommend_comment: true,
    is_party_enabled: false,
    premium_room_type: 0,
    next_score: 0,
    is_onlive: false,
    room_id: 400714,
  },
  {
    prev_league_id: null,
    image_list: [],
    banner_list: null,
    is_talk_online: false,
    award_list: null,
    push_send_status: {},
    performer_name: "",
    follower_num: 152125,
    live_continuous_days: 0,
    next_league_id: null,
    live_id: 0,
    league_id: 0,
    is_official: true,
    is_follow: false,
    voice_list: [],
    show_rank_subdivided: "Excluded",
    event: null,
    is_birthday: false,
    description:
      "Name: Gabriela Abigail Mewengkang\r\nBirthday: 7 August 2006\r\nBirthplace: Jakarta\r\nBlood type: B+\r\nZodiac signs:  Leo\r\nHobby: Dance, Listening to Music, Drawing\r\n\r\nTwitter: AM_EllaJKT48\r\nInstagram: jkt48.ella.a",
    live_tags: [],
    genre_id: 102,
    displayed_medals: [],
    prev_score: 0,
    youtube_id: "eq0s1atl_K0",
    visit_count: 0,
    recommend_comment_list: [
      {
        created_at: 1689183737,
        comment: "walaupun baru kemarin sr tapi aku udah rindu sr mu ella 😿",
        user: {
          name: "ELLAY",
          image: "https://static.showroom-live.com/image/avatar/22.png?v=95",
        },
      },
      {
        created_at: 1689176199,
        comment: "Ella kapan showroom",
        user: {
          name: "_Adenz",
          image: "https://static.showroom-live.com/image/avatar/19.png?v=95",
        },
      },
      {
        created_at: 1689005695,
        comment: "semangat cintaaa",
        user: {
          name: "Rajaa",
          image: "https://static.showroom-live.com/image/avatar/39.png?v=95",
        },
      },
    ],
    current_live_started_at: 0,
    next_show_rank_subdivided: "",
    share_text_live:
      "Ella /エラ（JKT48） Broadcasting!\nhttps://www.showroom-live.com/r/JKT48_Ella?t=1689385362",
    sns_list: [
      {
        icon: "https://static.showroom-live.com/assets/img/icon/sns/youtube.png",
        url: "https://www.youtube.com/watch?v=eq0s1atl_K0",
        name: "Youtube",
      },
    ],
    recommend_comments_url:
      "https://www.showroom-live.com/room/recommend_comments?room_id=400715",
    share_url: "https://www.showroom-live.com/room/profile?room_id=400715",
    room_url_key: "JKT48_Ella",
    league_label: "",
    is_live_tag_campaign_opened: false,
    avatar: null,
    share_url_live: "https://www.showroom-live.com/r/JKT48_Ella?t=1689385362",
    prev_show_rank_subdivided: "",
    is_talk_opened: false,
    image_square:
      "https://static.showroom-live.com/image/room/cover/33b9a09551fb56e388c636720e88c310983d759c7be62230d59aa4a84303e1dc_square_m.jpeg?v=1685542674",
    recommend_comment_post_url:
      "https://www.showroom-live.com/room/recommend_comments?room_id=400715#post",
    genre_name: "Idol",
    room_name: "Ella /エラ（JKT48）",
    birthday: 81961200,
    room_level: 113,
    party_live_status: 0,
    party: {},
    ec_config: { sales_available: 0, is_external_ec: 0, links: [] },
    image:
      "https://static.showroom-live.com/image/room/cover/33b9a09551fb56e388c636720e88c310983d759c7be62230d59aa4a84303e1dc_m.jpeg?v=1685542674",
    recommend_comment_open_status: 1,
    main_name: "Ella /エラ（JKT48）",
    view_num: 0,
    has_more_recommend_comment: true,
    is_party_enabled: false,
    premium_room_type: 0,
    next_score: 0,
    is_onlive: false,
    room_id: 400715,
  },
  {
    prev_league_id: null,
    image_list: [],
    banner_list: null,
    is_talk_online: false,
    award_list: null,
    push_send_status: {},
    performer_name: "",
    follower_num: 134607,
    live_continuous_days: 0,
    next_league_id: null,
    live_id: 0,
    league_id: 0,
    is_official: true,
    is_follow: false,
    voice_list: [],
    show_rank_subdivided: "Excluded",
    event: null,
    is_birthday: false,
    description:
      "Name: Indira Putri Seruni\r\nBirthday: 26 April 2004\r\nBirthplace: Bandung\r\nBlood type: A\r\nZodiac signs: Taurus\r\nHobby: Dance\r\n\r\nTwitter: SP_IndiraJKT48\r\nInstagram: jkt48.indira.s",
    live_tags: [],
    genre_id: 102,
    displayed_medals: [],
    prev_score: 0,
    youtube_id: "eq0s1atl_K0",
    visit_count: 0,
    recommend_comment_list: [
      {
        created_at: 1689157107,
        comment: "kapan sr ?\n",
        user: {
          name: "Zahra",
          image: "https://static.showroom-live.com/image/avatar/2.png?v=95",
        },
      },
      {
        created_at: 1688987621,
        comment: "Kapan Sr Dir",
        user: {
          name: "Rizky Tian",
          image: "https://static.showroom-live.com/image/avatar/5.png?v=95",
        },
      },
      {
        created_at: 1687354924,
        comment: "p, ga sr lagi?",
        user: {
          name: "PacarShani",
          image:
            "https://static.showroom-live.com/image/avatar/1066960.png?v=95",
        },
      },
    ],
    current_live_started_at: 0,
    next_show_rank_subdivided: "",
    share_text_live:
      "Indira /インディラ（JKT48） Broadcasting!\nhttps://www.showroom-live.com/r/JKT48_Indira?t=1689385362",
    sns_list: [
      {
        icon: "https://static.showroom-live.com/assets/img/icon/sns/youtube.png",
        url: "https://www.youtube.com/watch?v=eq0s1atl_K0",
        name: "Youtube",
      },
    ],
    recommend_comments_url:
      "https://www.showroom-live.com/room/recommend_comments?room_id=400716",
    share_url: "https://www.showroom-live.com/room/profile?room_id=400716",
    room_url_key: "JKT48_Indira",
    league_label: "",
    is_live_tag_campaign_opened: false,
    avatar: null,
    share_url_live: "https://www.showroom-live.com/r/JKT48_Indira?t=1689385362",
    prev_show_rank_subdivided: "",
    is_talk_opened: false,
    image_square:
      "https://static.showroom-live.com/image/room/cover/80e7ab4bb7445c959ca2bff7c44dac4cc7353bddc0d3c70b6928c00f67ccfc53_square_m.jpeg?v=1685542774",
    recommend_comment_post_url:
      "https://www.showroom-live.com/room/recommend_comments?room_id=400716#post",
    genre_name: "Idol",
    room_name: "Indira /インディラ（JKT48）",
    birthday: 73062000,
    room_level: 49,
    party_live_status: 0,
    party: {},
    ec_config: { sales_available: 0, is_external_ec: 0, links: [] },
    image:
      "https://static.showroom-live.com/image/room/cover/80e7ab4bb7445c959ca2bff7c44dac4cc7353bddc0d3c70b6928c00f67ccfc53_m.jpeg?v=1685542774",
    recommend_comment_open_status: 1,
    main_name: "Indira /インディラ（JKT48）",
    view_num: 0,
    has_more_recommend_comment: true,
    is_party_enabled: false,
    premium_room_type: 0,
    next_score: 0,
    is_onlive: false,
    room_id: 400716,
  },
  {
    prev_league_id: null,
    image_list: [],
    banner_list: null,
    is_talk_online: false,
    award_list: null,
    push_send_status: {},
    performer_name: "",
    follower_num: 121041,
    live_continuous_days: 1,
    next_league_id: null,
    live_id: 0,
    league_id: 0,
    is_official: true,
    is_follow: false,
    voice_list: [],
    show_rank_subdivided: "Excluded",
    event: null,
    is_birthday: false,
    description:
      "Name: Jesslyn Elly\r\nBirthday: 13 September 2001\r\nBirthplace: Jakarta\r\nBlood type: O\r\nZodiac signs:  Virgo\r\nHobby: Reading, Playing Music, Traveling\r\n\r\nTwitter: SE_LynJKT48\r\nInstagram:jkt48.lyn.s",
    live_tags: [],
    genre_id: 102,
    displayed_medals: [],
    prev_score: 0,
    youtube_id: "eq0s1atl_K0",
    visit_count: 0,
    recommend_comment_list: [
      {
        created_at: 1689090802,
        comment: "semangat lyn",
        user: {
          name: "Mase",
          image: "https://static.showroom-live.com/image/avatar/19.png?v=95",
        },
      },
      {
        created_at: 1689091155,
        comment: "ci Lyn mungil kesayangan aku 🥰",
        user: {
          name: "Denyclo",
          image:
            "https://static.showroom-live.com/image/avatar/1047728.png?v=95",
        },
      },
      {
        created_at: 1688618962,
        comment:
          "Halo ci lyn, Izinkan aku untuk mengikuti keseharian kamu. Semangat trs yaa, janlup minum air putih ci dan jaga kesehatan",
        user: {
          name: "apaandahhh",
          image: "https://static.showroom-live.com/image/avatar/28.png?v=95",
        },
      },
    ],
    current_live_started_at: 0,
    next_show_rank_subdivided: "",
    share_text_live:
      "Lyn /リーン（JKT48） Broadcasting!\nhttps://www.showroom-live.com/r/JKT48_Lyn?t=1689385362",
    sns_list: [
      {
        icon: "https://static.showroom-live.com/assets/img/icon/sns/youtube.png",
        url: "https://www.youtube.com/watch?v=eq0s1atl_K0",
        name: "Youtube",
      },
    ],
    recommend_comments_url:
      "https://www.showroom-live.com/room/recommend_comments?room_id=400717",
    share_url: "https://www.showroom-live.com/room/profile?room_id=400717",
    room_url_key: "JKT48_Lyn",
    league_label: "",
    is_live_tag_campaign_opened: false,
    avatar: null,
    share_url_live: "https://www.showroom-live.com/r/JKT48_Lyn?t=1689385362",
    prev_show_rank_subdivided: "",
    is_talk_opened: false,
    image_square:
      "https://static.showroom-live.com/image/room/cover/261d835846ccd54052d7bede79f89171d1f79af054ada2fecf81086644ff6ea4_square_m.jpeg?v=1685542810",
    recommend_comment_post_url:
      "https://www.showroom-live.com/room/recommend_comments?room_id=400717#post",
    genre_name: "Idol",
    room_name: "Lyn /リーン（JKT48）",
    birthday: 85158000,
    room_level: 65,
    party_live_status: 0,
    party: {},
    ec_config: { sales_available: 0, is_external_ec: 0, links: [] },
    image:
      "https://static.showroom-live.com/image/room/cover/261d835846ccd54052d7bede79f89171d1f79af054ada2fecf81086644ff6ea4_m.jpeg?v=1685542810",
    recommend_comment_open_status: 1,
    main_name: "Lyn /リーン（JKT48）",
    view_num: 0,
    has_more_recommend_comment: true,
    is_party_enabled: false,
    premium_room_type: 0,
    next_score: 0,
    is_onlive: false,
    room_id: 400717,
  },
  {
    prev_league_id: null,
    image_list: [],
    banner_list: null,
    is_talk_online: false,
    award_list: null,
    push_send_status: {},
    performer_name: "",
    follower_num: 124790,
    live_continuous_days: 1,
    next_league_id: null,
    live_id: 0,
    league_id: 0,
    is_official: true,
    is_follow: false,
    voice_list: [],
    show_rank_subdivided: "Excluded",
    event: null,
    is_birthday: false,
    description:
      "Name: Raisha Syifa Wardhana\r\nBirthday: 11 November 2007\r\nBirthplace: Jakarta\r\nBlood type: AB+\r\nZodiac signs: Scorpio\r\nHobby: Dance, Sing, Sport\r\n\r\nTwitter: SW_RaishaJKT48\r\nInstagram: jkt48.raisha.s",
    live_tags: [],
    genre_id: 102,
    displayed_medals: [],
    prev_score: 0,
    youtube_id: "eq0s1atl_K0",
    visit_count: 0,
    recommend_comment_list: [
      {
        created_at: 1689350485,
        comment: "Hi Raisha",
        user: {
          name: "nanas",
          image:
            "https://static.showroom-live.com/image/avatar/1066455.png?v=95",
        },
      },
      {
        created_at: 1689350637,
        comment: "ooooo",
        user: {
          name: "Pikiiiii",
          image:
            "https://static.showroom-live.com/image/avatar/1061737.png?v=95",
        },
      },
      {
        created_at: 1689342617,
        comment: "Hi Raisha! How ya goin'?",
        user: {
          name: "Timothy Natanael Sebastian",
          image: "https://static.showroom-live.com/image/avatar/6.png?v=95",
        },
      },
    ],
    current_live_started_at: 0,
    next_show_rank_subdivided: "",
    share_text_live:
      "Raisha /ライシャ（JKT48） Broadcasting!\nhttps://www.showroom-live.com/r/JKT48_Raisha?t=1689385362",
    sns_list: [
      {
        icon: "https://static.showroom-live.com/assets/img/icon/sns/youtube.png",
        url: "https://www.youtube.com/watch?v=eq0s1atl_K0",
        name: "Youtube",
      },
    ],
    recommend_comments_url:
      "https://www.showroom-live.com/room/recommend_comments?room_id=400718",
    share_url: "https://www.showroom-live.com/room/profile?room_id=400718",
    room_url_key: "JKT48_Raisha",
    league_label: "",
    is_live_tag_campaign_opened: false,
    avatar: null,
    share_url_live: "https://www.showroom-live.com/r/JKT48_Raisha?t=1689385362",
    prev_show_rank_subdivided: "",
    is_talk_opened: false,
    image_square:
      "https://static.showroom-live.com/image/room/cover/b5e493484b3fdd07ebadfd478837295c9968208cf3721934b46611eca5cb92b8_square_m.jpeg?v=1685542844",
    recommend_comment_post_url:
      "https://www.showroom-live.com/room/recommend_comments?room_id=400718#post",
    genre_name: "Idol",
    room_name: "Raisha /ライシャ（JKT48）",
    birthday: 90255600,
    room_level: 59,
    party_live_status: 0,
    party: {},
    ec_config: { sales_available: 0, is_external_ec: 0, links: [] },
    image:
      "https://static.showroom-live.com/image/room/cover/b5e493484b3fdd07ebadfd478837295c9968208cf3721934b46611eca5cb92b8_m.jpeg?v=1685542844",
    recommend_comment_open_status: 1,
    main_name: "Raisha /ライシャ（JKT48）",
    view_num: 0,
    has_more_recommend_comment: true,
    is_party_enabled: false,
    premium_room_type: 0,
    next_score: 0,
    is_onlive: false,
    room_id: 400718,
  },
];
